#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="6.1.141" --arg="/boot/vmlinuz-6.1.141" /etc/kernel/postinst.d
exit 0
